# Generated by Django 5.1.3 on 2025-01-14 12:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_product_views_counter_alter_product_category_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="views_counter",
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите фото продукта",
                null=True,
                upload_to="catalog/image",
                verbose_name="Фото продукта",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.IntegerField(
                default=0,
                validators=[django.core.validators.MaxValueValidator(10000)],
                verbose_name="Цена за продукт",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated_at",
            field=models.DateField(
                blank=True,
                help_text="Введите дату последнего изменения",
                null=True,
                verbose_name="Дата последнего изменения",
            ),
        ),
    ]
